// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDBOoRzOS5V72rkgRJ2sM0Tpc1SHhYUcY',
    appId: '1:196603515364:web:695a83bf4debe8cbc777f1',
    messagingSenderId: '196603515364',
    projectId: 'flutterbase-75d80',
    authDomain: 'flutterbase-75d80.firebaseapp.com',
    storageBucket: 'flutterbase-75d80.appspot.com',
    measurementId: 'G-KPGQ4GPBF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgBFKQFBd0JKymNnAlWpmegz58dBAHEA0',
    appId: '1:196603515364:android:d2a018c12edc1be9c777f1',
    messagingSenderId: '196603515364',
    projectId: 'flutterbase-75d80',
    storageBucket: 'flutterbase-75d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZt-iubsh_XfdGkguYPDX49H8eN5X1LkA',
    appId: '1:196603515364:ios:16a12a65aef44554c777f1',
    messagingSenderId: '196603515364',
    projectId: 'flutterbase-75d80',
    storageBucket: 'flutterbase-75d80.appspot.com',
    iosBundleId: 'com.example.newproject222',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZt-iubsh_XfdGkguYPDX49H8eN5X1LkA',
    appId: '1:196603515364:ios:16a12a65aef44554c777f1',
    messagingSenderId: '196603515364',
    projectId: 'flutterbase-75d80',
    storageBucket: 'flutterbase-75d80.appspot.com',
    iosBundleId: 'com.example.newproject222',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDBOoRzOS5V72rkgRJ2sM0Tpc1SHhYUcY',
    appId: '1:196603515364:web:d673dbcef0d364fac777f1',
    messagingSenderId: '196603515364',
    projectId: 'flutterbase-75d80',
    authDomain: 'flutterbase-75d80.firebaseapp.com',
    storageBucket: 'flutterbase-75d80.appspot.com',
    measurementId: 'G-5Z6WW5S0VH',
  );
}
